<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
	<%@ page
	import="java.util.*, java.text.*, tel_ran.tests.controller.Maintenance"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
 <link
	href='<c:url value="/static/css_folder/maintenance_styles/CreateQuestionPage.css"></c:url>'
	rel="stylesheet"> 
<script type="text/javascript">
$(document).ready(function(){
	$("#inputCategoryField").css("display","none");
	
	$("#addingForm").keyup(function(){
		var $catSelect = $("#catSel").val();
		if($catSelect != "none"){
			$("#inputCategoryField").css("display","none");
			$("#inputCategoryField").val(" ");
		}
		
	 var question_text = document.question_adding_form.questionText.value;	
		if(question_text.length > 3){
			var $catSel = $("#catSel").val();			
			if($catSel.length != 0){// stub  test if category selected				
			var answer = document.question_adding_form.correctAnswer.value;	
			var codeT = document.question_adding_form.codeText.value;
			if(answer.length == 1 || codeT.length != 0){							
				 document.getElementsByName("button_send")[0].disabled = false;
			}else{
				document.getElementsByName("button_send")[0].disabled = true;
			}				
			}else{
				document.getElementsByName("button_send")[0].disabled = true;
			}
		}else{
			 document.getElementsByName("button_send")[0].disabled = true;
		}
	});
	////
	//test_code
	///// AJAX Tast Code Case Request/Response
	$("#test_code").click(function(){							
		var $codeInText = $('#codeText').val();			
		
		$.ajax({type: "POST",
			url: "handler-user-code",
			data: "userCode" + $codeInText,					
			success: function(response){
				// we have the response				
				if(response.status == "SUCCESS"){								
					alert(response.result);
													 
				}else if(response.status == "ERROR"){  
					alert("code wrong try again!!!");
				}		
			},
			error: function(e){
				alert('Error: ' + e);			
			}
		}); 
	});
	
	$("#newCategoryCreating").click(function(){
		var $catSelect = $("#catSel").val();
		if($catSelect == "none"){
			$("#inputCategoryField").css("display","block");			
		}else{
			$("#inputCategoryField").css("display","none");
			$("#inputCategoryField").val(" ");
		}		
	});
});
</script>

<title>ADDING</title>
</head>
<body>
	<p>Creating new Question</p>
	<form action="add_actions" method="post" id="addingForm"
		name="question_adding_form">
		<table>
			<tr>
				<th class="thFloatText">Input Question text</th>
				<td class="tdFloatContent"><textarea name="questionText"
						id="questionText" rows="3"
						placeholder="Type here question text or description for image"></textarea></td>
			</tr>
			<tr>
				<th class="thFloatText">Question Index Number</th>
				<td class="tdFloatContent"><input type="text"
					name="questionIndex" value="0"></td>
			</tr>
			<tr>
				<td class="thFloatText">
				<div id="newCategoryCreating" class="buttons">New Question Category</div>
				
				<select id="catSel" name="category">
				<option value="none">Select Question Category</option>				
				<%= Maintenance.AutoGeneratedInformationTextHTML()%>
				</select>
				</td>
				<td class="tdFloatContent">
				<input id="inputCategoryField" type="text" name="category" hidden="hidden" placeholder="Java,HTML,...">
				</td>
			</tr>  
			<tr><td class="tdFloatContent" colspan="2">
				<select name="levelOfDifficulty">
					<option value=1>level Of Difficulty</option>
					<option value=1>level  1</option>
					<option value=2>level  2</option>
					<option value=3>level  3</option>
					<option value=4>level  4</option>
					<option value=5>level  5</option>
					</select>
				</td>
			</tr>
			<tr><th class="thFloatText">Input Code by pattern<div>
				<pre class="preTextPatternCode">
				class main{
				NewCode() test = new NewCode();
				test.Foo();
				}
				
				public class NewCode{
				public NewCode(){}
				
				public Foo(){
				  //any action				
				}
				</pre></div></th>
				<td class="tdFloatContent"><textarea id="codeText" name="codeText" rows="14" cols="23"></textarea></td>
			</tr>			
			<tr><td class="tdFloatContent" colspan="2"><div class="buttons" id="test_code">Test Code</div></td>
			</tr>
			<tr id="answersTr">
				<th class="thFloatText">Input Answer</th>
				<td class="tdFloatContent">A. <textarea name="at1"></textarea><br>
					B. <textarea name="at2"></textarea><br> C. <textarea
						name="at3"></textarea><br> D. <textarea name="at4"></textarea><br>
				</td>
			</tr>
			<tr>
				<th class="thFloatText">Input Char a right question answer</th>
				<td class="tdFloatContent"><input type="text"
					name="correctAnswer" placeholder="D">
				</td>
			</tr>
			<tr>
				<th class="thFloatText">Input number answers on image</th>
				<td class="tdFloatContent"><input type="text"
					name="numberAnswersOnPicture" value="0"></td>
			</tr>
			<tr id="imageLinkTr">
				<th class="thFloatText">Image Link</th>
				<td class="tdFloatContent"><input type="text" name="imageLink"
					placeholder="/s7d9dejd78f6t4th47.jpg" /></td>
			</tr>
			<tr>
				<th colspan="2"><input name="button_send" id="button_send"
					type="submit" value="Add To DataBase" disabled></th>
			</tr>
		</table>
	</form>
	<br>

	<script type="text/javascript">
		document.write("${result}");
	</script>
	<a class="myButton" href='.'>home</a>&nbsp;&nbsp;&nbsp;&nbsp;
	<a class="myButton" href='update'>update (link for erase)</a>
</body>
</html>
