
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page
	import="java.util.*, java.text.*, tel_ran.tests.controller.Maintenance"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
 <link
	href='<c:url value="/static/css_folder/user_styles/IndexPage.css"></c:url>'
	rel="stylesheet">
<link
	href='<c:url value="/static/css_folder/style.css"></c:url>'
	rel="stylesheet">

<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script src="static/js_folder/maintenance_scripts/other_resurses_page.js"></script>
<script src="static/js_folder/header&&rightmenu_maintenace.js"></script>

<title>OTHER RESURSES</title>
</head>




<body>
	<div id="container">


 	  <div id="right_side">


	 	<div id="description">
		  	<div class="fillfromfile">
		<button id="readTextFromFile">Read text file on this computer</button>
	</div>
	<br>
	<div class="generateQuestions">
		<button id="generateQuestionsByCategory">Generate questions
			by categoy</button>
	</div>
	<br>
	<div id="formCategory" class="formCategory">
		<label>Select a category questions</label>
		<form action='moduleForBuildingQuestions'>
		    <div>
		    <label>&nbsp;</label>
			<select name="category" id="categoryOfQuestions">
				<option value="none">Select Category For Generation</option>
			</select>
			</div>
			
			<div>
			<label>Number of questions :</label>
			<input type="number"
				name='nQuestions' value='50' size="5"> 
			</div>
			<div>
				<label>Level Of difficulty :</label>
				<input type="number" name='levelOfDifficulty' value='3'
				size="5"> 
				</div>
				<div>
				<input type='submit' value="Generate Questions">
				</div>
		</form>
	</div>
	<br>
	<div id="fileaddform" class="formFileAdding">
		<h2>Auto Complete Data Base from external file</h2><br>
		<label> Please choice specific file to fill data base</label>
		<form action="add_from_file_actions" name="add_from_file_actions">
			<input type="file" id="fileaddformInput" name="fileaddformInput"
				onchange='openFile(event)'> <br>
			<textArea hidden="hidden" name="textfromfile" id="hiddenTextFromFile"></textArea>
			<input type='submit' value="Send Questions">
		</form>
	</div>
	<br>
	<label><%=Maintenance.AutoGeneratedInformationTextHTML()%></label>
	<br>
	 	</div><!--end of our description area-->
				 	<div id="additional_area"> </div>
				 		
 	  </div><!--end of right area-->
 	


 	<div id="footer_area">
	
 	<p> Copyright &copy; 2014 HrTrueTest</p>
	</div>
</div>
</body>
</html>