
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page
	import="java.util.*, java.text.*, tel_ran.tests.controller.Maintenance"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<title>Maintenance service</title>
<script type="text/javascript">
    //// JQuery actions
	$(document).ready(function() {
	///// AJAX  Request/Response creating category for generated questions
	var $RtemP = "request";
		$.ajax({type: "POST",
			url: "categoryCreationAction",
			data: "request" + $RtemP,					
			success: function(response){
				// we have the response				
				if(response.status == "SUCCESS"){
					var gres = response.result;
					$('#categoryOfQuestions').html(gres);													 
				}else{
					alert("wrong BES not Responsed");
				}		
			},
			error: function(e){
				alert('Error: ' + e);			
			}
		}); 
	    ////
		$(".formCategory").css("display", "none");
		$(".formFileAdding").css("display", "none");
		////
		$("#readTextFromFile").click(function() {
			$(".generateQuestions,.fillfromfile").css("display", "none");
			$(".formFileAdding").css("display", "block");
		});
		////
		$("#generateQuestionsByCategory").click(function() {
			$(".generateQuestions,.fillfromfile").css("display", "none");
			$(".formCategory").css("display", "block");
		});
	});
	/////
	var openFile = function(event) {
		var input = event.target;
		var reader = new FileReader();
		reader.onload = function() {
			var text = reader.result;
			$("#hiddenTextFromFile").text(reader.result);
		};
		reader.readAsText(input.files[0]);
	};
</script>
</head>
<body>
	<div class="fillfromfile">
		<button id="readTextFromFile">Read text file on this computer</button>
	</div>
	<br>
	<div class="generateQuestions">
		<button id="generateQuestionsByCategory">Generate questions
			by categoy</button>
	</div>
	<br>
	<div id="formCategory" class="formCategory">
		<br>Select a category questions<br>
		<form action='moduleForBuildingQuestions'>
			<select name="category" id="categoryOfQuestions">
				<option value="none">Select Category For Generation</option>
			</select> <br>Enter the number of questions : <input type="number"
				name='nQuestions' value='50' size="5"><br> <input
				type='submit' value="Generate Questions">
		</form>
	</div>
	<br>
	<div id="fileaddform" class="formFileAdding">
		<p>Auto Complete Data Base from external file</p>
		<br> Please choice specific file to fill data base <br> <br>
		<form action="add_from_file_actions" name="add_from_file_actions">
			<input type="file" id="fileaddformInput" name="fileaddformInput"
				onchange='openFile(event)'> <br>
			<textArea hidden="hidden" name="textfromfile" id="hiddenTextFromFile"></textArea>
			<input type='submit' value="Send Questions">
		</form>
	</div>
	<br>
	<%=Maintenance.AutoGeneratedInformationTextHTML()%>
	<br>
	<a href=".">Home</a>
</body>
</html>