
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page
	import="java.util.*, java.text.*, tel_ran.tests.controller.Maintenance"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="static/js_folder/maintenance_scripts/other_resurses_page.js"></script>
<title>OTHER RESURSES</title>
</head>
<body>
	<div class="fillfromfile">
		<button id="readTextFromFile">Read text file on this computer</button>
	</div>
	<br>
	<div class="generateQuestions">
		<button id="generateQuestionsByCategory">Generate questions
			by categoy</button>
	</div>
	<br>
	<div id="formCategory" class="formCategory">
		<br>Select a category questions<br>
		<form action='moduleForBuildingQuestions'>
			<select name="category" id="categoryOfQuestions">
				<option value="none">Select Category For Generation</option>
			</select> <br>Number of questions : <input type="number"
				name='nQuestions' value='50' size="5"> <br>Level Of
			difficulty : <input type="number" name='levelOfDifficulty' value='3'
				size="5"> <br> <input type='submit'
				value="Generate Questions">
		</form>
	</div>
	<br>
	<div id="fileaddform" class="formFileAdding">
		<p>Auto Complete Data Base from external file</p>
		<br> Please choice specific file to fill data base <br> <br>
		<form action="add_from_file_actions" name="add_from_file_actions">
			<input type="file" id="fileaddformInput" name="fileaddformInput"
				onchange='openFile(event)'> <br>
			<textArea hidden="hidden" name="textfromfile" id="hiddenTextFromFile"></textArea>
			<input type='submit' value="Send Questions">
		</form>
	</div>
	<br>
	<%=Maintenance.AutoGeneratedInformationTextHTML()%>
	<br>
	<a href=".">Home</a>
</body>
</html>