<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page
import="java.util.*, java.text.*, tel_ran.tests.controller.Maintenance"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
 <link
	href='<c:url value="/static/css_folder/maintenance_styles/CreateQuestionPage.css"></c:url>'
	rel="stylesheet"> 
<script src="static/js_folder/maintenance_scripts/add_question_page.js"></script><title>ADDING</title>
</head>
<body>
	<p>Creating new Question</p>
	<form action="add_actions" method="post" id="addingForm"
name="question_adding_form">
<table>
<!-- ----------------------------------------------------------------------------------- Question text field (unique!!!) --> 
	<tr>
		<th class="thFloatText">Input Question text</th>
		<td class="tdFloatContent"><textarea name="questionText"
				id="questionText" rows="3"
				placeholder="Write essence of the question, or the question text"></textarea></td>
	</tr>
	<!-- ----------------------------------------------------------------------------------- description Text field (optional) --> 
	<tr>
		<th class="thFloatText">Input Description text</th>
		<td class="tdFloatContent"><textarea name="descriptionText"
				id="descriptionText" rows="3"
				placeholder="Write a description of the proposed objectives"></textarea></td>
	</tr>
	<!-- ----------------------------------------------------------------------------------- id of question (optional) -->
<tr>
	<th class="thFloatText">Question Index Number</th>
	<td class="tdFloatContent"><input type="text" name="questionIndex" value="0"></td>
</tr>	
<!-- ----------------------------------------------------------------------------------- metaCategory of question (getting from DB) -->
<tr>
	<td class="thFloatText">
	<div id="newMetaCategoryCreating" class="buttons">Meta Category</div>
	<select id="mCatSel" name="metaCategory">
	<option value="none">Select Question Category</option>				
	<%-- <%= Maintenance.AutoGeneratedInformationTextHTML()%> --%>
</select>
</td>
<td class="tdFloatContent">
<input id="inputMetaCategoryField" type="text" name="metaCategory" hidden="hidden" placeholder="Programming">
</td>
   </tr>  
<!-- ----------------------------------------------------------------------------------- Category of question (getting from DB) -->
<tr>
	<td class="thFloatText">
	<div id="newCategoryCreating" class="buttons">New Question Category</div>	
	<select id="catSel" name="category">
	<option value="none">Select Question Category</option>				
	<%= Maintenance.AutoGeneratedInformationTextHTML()%>
	</select>
	</td>
	<td class="tdFloatContent">
	<input id="inputCategoryField" type="text" name="category" hidden="hidden" placeholder="Java,HTML,...">
	</td>
</tr> 
<!-- ----------------------------------------------------------------------------------- Question level Of Difficulty () --> 
<tr><td class="tdFloatContent" colspan="2">
	<select name="levelOfDifficulty">
		<option value=1>level Of Difficulty</option>
		<option value=1>level  1</option>
		<option value=2>level  2</option>
		<option value=3>level  3</option>
		<option value=4>level  4</option>
		<option value=5>level  5</option>
		</select>
	</td>
</tr>
<!-- ----------------------------------------------------------------------------------- code in text for testing () --> 
<tr>
<th class="thFloatText">Input Code by pattern<div>
	<pre class="preTextPatternCode">
	Write the implementation!!!
	your interface,
	or your method.
	</pre></div></th>
	<td class="tdFloatContent"><textarea id="codeText" name="codeText" rows="14" cols="23"></textarea></td>
</tr>
<!-- ----------------------------------------------------------------------------------- Button test code (AJAX) --> 			
<tr>
<td class="tdFloatContent" colspan="2">
<div class="buttons" id="test_code">Test Code</div>
</td>
</tr>
<!-- ----------------------------------------------------------------------------------- Answers for the Question (Write variants wrong answers and 1 correct this issue) --> 
<tr id="answersTr">
	<th class="thFloatText">Write variants wrong<br> answers and one correct this issue</th><!--TO DO auto creating ansver field by nNumber !!!(JQuery)  -->
	<td class="tdFloatContent">A. <textarea name="at1"></textarea><br>
		B. <textarea name="at2"></textarea><br> C. <textarea
			name="at3"></textarea><br> D. <textarea name="at4"></textarea><br>
	</td>
</tr>
<!-- ----------------------------------------------------------------------------------- answer char input  (1 CHAR !!! or TRUE/FALSE or empty input !!!) --> 
<tr>
	<th class="thFloatText">language name</th>
	<td class="tdFloatContent"><input type="text"
		name="languageName" placeholder="Java">
	</td>
</tr>
<!-- ----------------------------------------------------------------------------------- answer char input  (1 CHAR !!! or TRUE/FALSE or empty input !!!) --> 
<tr>
	<th class="thFloatText">Input Char a right question answer</th>
	<td class="tdFloatContent"><input type="text"
		name="correctAnswer" placeholder="D">
	</td>
</tr>
<!-- ----------------------------------------------------------------------------------- numberAnswersOnPicture () --> 
<tr>
	<th class="thFloatText">Input number answers on image</th>
	<td class="tdFloatContent"><input type="text"
		name="numberAnswersOnPicture" value="0"></td>
</tr>
<!-- -----------------------------------------------------------------------------------  () --> 
<!--
TO DO upload image from 
user computer, and convert to Base64 ???, for send to Service(BES),
and save in standard folder (questions) on server in format .jpg
-->
<tr id="imageLinkTr">
	<th class="thFloatText">Upload Image</th>	
	<td class="tdFloatContent">
	<input type="text" name="fileLocationLink"	placeholder="/MetaCategory/Category[if exist]/questionPictureName.jpg" />	
	</td>	
	</tr>
	<!-- ----------------------------------------------------------------------------------- Button send return to index page    () --> 
	<tr>
		<th colspan="2"><input name="button_send" id="button_send"
			type="submit" value="Add To DataBase" disabled></th>
	</tr>
</table>
</form>
<br>

<script type="text/javascript">
document.write("${result}");
</script>
	<a class="myButton" href='.'>home</a>&nbsp;&nbsp;&nbsp;&nbsp;
	<a class="myButton" href='update'>search</a>
</body>
</html>
