
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page
	import="java.util.*, java.text.*, tel_ran.tests.controller.Maintenance"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
 <head>
 <link
	href='<c:url value="/static/css_folder/maintenance_styles/MaintenanceHomePage.css"></c:url>'
	rel="stylesheet"> 
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<title>LOGIN</title>
<style type="text/css">
#menuButton{
 display:none; 

}
</style>
</head>
<body>	
	<br>
	<div id="menuButton">
		<div id='homepage'>
			<a class='myButton' href='maintenanceadd'>Create new question</a> <br/>
			<a class='myButton' href='update'>Update/Delete Question</a>
			<a class='myButton' href='otherResursCreationMethod'>Adding questions from Other Resurses</a> 			
			<a class='myButton' href='.'>Home</a>
		</div>
	</div>	
	<br>
	<%= Maintenance.AutoGeneratedHTMLForm() %>	<!-- this methods work only for MaintenanceSignInPage !!!  -->	
</body> 
</html>
