package tel_ran.tests.controller;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.SessionAttributes;

import tel_ran.tests.controller.AbstractAdminActions.JsonResponse;
import tel_ran.tests.strings.IMessages;
import tel_ran.tests.users.Visitor;

@Controller
@Scope("session") /*session timer default = 20min*/
@SessionAttributes({"role","visitor"})
public abstract class AController {
	
	public final static String ROLE = "role"; 
	public final static String VISITOR = "visitor"; 
	public static final String RESULT = "result";
	public static final String ACCOUNT_INFO = "account";
	
	public static String metaCategoryListHTML;
		
	public static StringBuffer autoGeneratedHTMLFormText = new StringBuffer();
	public static  StringBuffer autoGeneratedInformationTextHTML = new StringBuffer();

	// ------------------------- IN THE BEGINNING ---------------------------------------- //
	
	@ModelAttribute("role")
	public int populateRole() {
		return 0;
	}
	
	@ModelAttribute(VISITOR)
	public Visitor populateHandler() {
		return new Visitor(0);
	}
	
	protected void changeAttributes(Visitor visitor, Model model) {
		model.addAttribute(ROLE, visitor.getRoleNumber());
		model.addAttribute(VISITOR, visitor);	
		System.out.println("I'm here! My visitor = " + visitor.getCompanyName());
	}
	
	// -------------------------- TEXT FOR HTML --------------------------------------------- //
	protected void addTextHTML(String string) {
		autoGeneratedInformationTextHTML.append(string);
	}
	
	
	protected void clearHtmlText() {
		if(autoGeneratedHTMLFormText!=null)
			autoGeneratedHTMLFormText.delete(0, autoGeneratedHTMLFormText.length());// clear stringbuffer		
	}
	
	protected String getOptionsFromList(List<String> lst, String message) {
		StringBuilder result = new StringBuilder();
		if (lst != null) {			
			for (String tresR : lst) {	
				if(tresR!=null)
				result.append("<option value='" + tresR + "'> "+ tresR + "</option>");					
			}				
		} else {
			result.append(message);
		}
		return result.toString();
	}

	protected class JsonResponse {
		private String status = null;
		private Object result = null;
		public String getStatus() {
			return status;
		}
		public void setStatus(String status) {
			this.status = status;
		}
		public Object getResult() {
			return result;
		}
		public void setResult(Object result) {
			this.result = result;
		}
	}
	
	
	

}
