<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page
import="java.util.*, java.text.*, tel_ran.tests.controller.AbstractAdminActions"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
 <link
	href='<c:url value="/static/css_folder/user_styles/IndexPage.css"></c:url>'
	rel="stylesheet">
<link
	href='<c:url value="/static/css_folder/style.css"></c:url>'
	rel="stylesheet">
 <link
	href='<c:url value="/static/css_folder/maintenance_styles/CreateQuestionPage.css"></c:url>'
	rel="stylesheet"> 
<style>
	#resultDB{
		color: #aa0000;
		font-size: 20px;
    	font-weight: bold;
	}
	#button_OK{
		margin-left: 40px;
		margin-top: 8px;
	}
</style>
<script src="static/js_folder/maintenance_scripts/add_question_page.js">
</script>
<script src="static/js_folder/header&&rightmenu_company.js">
</script>	
<title>COMPANY ADDING QUESTION</title>
</head>
<body>
	<div id="container">

 	  <div id="right_side_company">
	<div id="formDiv">
	<h2>Creating new Question</h2>
	<form id="addingForm" name="question_adding_form">
      <!--  metaCategory of question (getting from DB) -->
        <div id="longdiv">
            <label>Meta Category</label>
            
            <select id="mCatSel" name="metaCategory">
            <option value="none">Select Question Category</option>
            	<option value="American Test">American Test</option>
                <option value="Open Question">Open Question</option>					
            <%-- <%= Maintenance.AutoGeneratedInformationTextHTML()%> --%>
            </select>
            &nbsp;
            <input id="inputMetaCategoryField" type="text" name="metaCategory"  hidden="hidden" placeholder="Programming">
 		</div>
        
        <!-- Category of question (getting from DB) -->
        
        <div id="longdiv" >
            <label>Question Category</label>
            <select id="catSel" name="category1">
            <option value="none">Select Question Category</option>	
            <option value="Create company category">Create new category</option>   
            <%= AbstractAdminActions.AutoGeneratedInformationTextHTML()%>
            </select> &nbsp;
            <input id="inputCategoryField" type="text" name="category" hidden="hidden" placeholder="Java,HTML,...">
 		</div>
        <div id="compcategory">
	        <label>Company category </label>
	        <input type="text" name="compcategory" id="compcategorytosend" />
       
		</div>
        <!-- Question level Of Difficulty () --> 
        <div>
            <label>Level of difficulty</label>
            <select id="levelOfDifficulty" name="levelOfDifficulty">
                <option value=1>level Of Difficulty</option>
                <option value=1>level  1</option>
                <option value=2>level  2</option>
                <option value=3>level  3</option>
                <option value=4>level  4</option>
                <option value=5>level  5</option>
            </select>
 		</div>
 		
        <!-- code in text for testing () --> 
        <div id = "questionDescription">
            <label>Question description <br />
            
            </label> 
            <textarea id="descriptionText" name="descriptionText" rows="14" cols="23"></textarea>
             <br />
            
 		</div>
         
        <div id = "codepattern">
            <label>Input Code by pattern <br />
             <p class="preTextPatternCode">
                Write the implementation!!!
                Your interface,
                or your method.
			</p>
            
            </label> 
            <textarea id="codeText" name="codeText" rows="14" cols="23"></textarea>
             <br />
       </div>
       
       <div id = "imageupload">
            <label>Upload Image</label>
            
           <input id ="takeFile" type="file"/>
            
 		</div>
       
        <div id = "americanquestion">
	        <!-- Button test code (AJAX) -->
	        <div>
	            <label>Test Code A</label>
	            <textarea id="at1" name="at1"></textarea>
	 		</div>
	        <div>
	            <label>Test Code B</label>
	            <textarea id="at2" name="at2"></textarea>
	 		</div>
	        <div>
	            <label>Test Code C</label>
	            <textarea id="at3" name="at3"></textarea>
	 		</div>
	        <div>
	            <label>Test Code D</label>
	            <textarea id="at4" name="at4"></textarea>
	 		</div>
	        
	        <!-- answer char input  (1 CHAR !!! or TRUE/FALSE or empty input !!!) --> 
	        <div>
	            <label>Input Char a right question answer</label>
	            <input type="text" id="correctAnswer" name="correctAnswer" placeholder="D">
	 		</div>
	        
 		</div> <!-- end american question div --> 
        <!--
        TO DO upload image from 
        user computer, and convert to Base64 ???, for send to Service(BES),
        and save in standard folder (questions) on server in format .jpg
        -->

        <div>
            <label>&nbsp;</label>
            
            <input name="button_send" id="button_send"
			type="button" value="Add To DataBase">
 		</div>
        <div id="resultDB"></div>
        <input id="button_OK" type="button" value="OK" style="display: none">
     
    </form>
    
        </div>			 		
 	  </div><!--end of right area-->
 	


 	<div id="footer_area">
	
 	<p> Copyright &copy; 2014 HrTrueTest</p>
	</div>
</div>
</body>
</html>