<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page
import="java.util.*, java.text.*, tel_ran.tests.controller.AbstractAdminActions"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
 <link
	href='<c:url value="/static/css_folder/user_styles/IndexPage.css"></c:url>'
	rel="stylesheet">
<link
	href='<c:url value="/static/css_folder/style.css"></c:url>'
	rel="stylesheet">
 <link
	href='<c:url value="/static/css_folder/maintenance_styles/CreateQuestionPage.css"></c:url>'
	rel="stylesheet"> 
<style>
	#resultDB{
		color: #aa0000;
		font-size: 20px;
    	font-weight: bold;
	}
	#button_OK{
		margin-left: 40px;
		margin-top: 8px;
	}
</style>
<script src="static/js_folder/maintenance_scripts/add_question_page.js">
</script>
<script src="static/js_folder/header&&rightmenu_company.js">
</script>	
<title>COMPANY ADDING QUESTION</title>
</head>
<body>
	<div id="container">

 	  <div id="right_side_company">
	<div id="formDiv">
	<h2>Creating new Question</h2>
	<form id="addingForm" name="question_adding_form">
      <!--  metaCategory of question (getting from DB) -->
         <div class="longdiv1">
                    <label>Type of question</label>

                    <select class="selectLine" id="mCatSel" name="metaCategory" required="required">
                        <option disabled selected="selected">Choose the type</option>
                        <option value="American Test">American Test</option>
                        <option value="Open Question">Open Question</option>
                        <%-- <%= Maintenance.AutoGeneratedInformationTextHTML()%> --%>
                    </select>
                    &nbsp;                    
                </div>
        
        <div id="aboutCategoryChosen"><p>Please, choose the type of the question. <br>
                    "American Test" has 2-4 options of answers, so the applicant should choose one of them. His answer will be checked automatically.<br>
                    "Open Question" doesn't have any options. The applicant should write his answer into a text field</div>
                    
        <!-- Category of question (getting from DB) -->
        
        <div id="questionCategory1" class="longdiv1" >
            <label>Question Category</label>
            <select class="selectLine" id="catSel" name="category1">
            <option value="none">Select Question Category</option>	
            <option value="Create company category">Create new category</option>   
            <%= AbstractAdminActions.AutoGeneratedInformationTextHTML()%>
            </select> &nbsp;
            <input id="inputCategoryField" type="text" name="category" hidden="hidden" placeholder="Java,HTML,...">
 		</div>
        <div id="compcategory">
	        <label>Company category </label>
	        <input type="text" name="compcategory" id="compcategorytosend" />
       
		</div>
        <!-- Question level Of Difficulty () --> 
        
       <div id="levelOfDifficultyForm">
                    <label>Level of difficulty</label>
                    <input type="radio" name="levelOfDifficulty" value="1">1
                    <input type="radio" name="levelOfDifficulty" value="2">2
                    <input type="radio" name="levelOfDifficulty" value="3" checked>3
                    <input type="radio" name="levelOfDifficulty" value="4">4
                    <input type="radio" name="levelOfDifficulty" value="5">5
        </div>
 		
        <!-- code in text for testing () --> 
        <div id = "questionDescription">
            <label>Question description <br />
            
            </label> 
            <textarea id="descriptionText" name="descriptionText" rows="14" cols="23"></textarea>
             <br />
            
 		</div>
         
        <div id = "codepattern">
            <label>Input Code by pattern <br />
             <p class="preTextPatternCode">
                Write the implementation!!!
                Your interface,
                or your method.
			</p>
            
            </label> 
            <textarea id="codeText" name="codeText" rows="14" cols="23"></textarea>
             <br />
       </div>
       
       <div id = "imageupload">
            <label>Upload Image</label>
            
           <input id ="takeFile" type="file"/>
            
 		</div>
       
      <div id = "americanquestion">

                    <br>
                    <div><h4>Options of answer</h4></div>
                    <br>
                    <!-- Button test code (AJAX) -->

                    <div>
                        <label>Option A</label>
                        <textarea id="at1" name="at1"></textarea>
                        <div class="correctAnswer">
                            <label>&nbsp;</label>
                            <input type="radio" name="correctAnswer" value="A">Correct answer</div>
                    </div>
                    <div>
                        <label>Option B</label>
                        <textarea id="at2" name="at2"></textarea>
                        <div class="correctAnswer">
                            <label>&nbsp;</label><input type="radio" name="correctAnswer" value="B">Correct answer</div>
                    </div>

                    <div>
                        <label>Option C</label>
                        <textarea id="at3" name="at3"></textarea>
                        <div class="correctAnswer">
                            <label>&nbsp;</label><input type="radio" name="correctAnswer" value="C">Correct answer</div>
                    </div>

                    <div>
                        <label>Option D</label>
                        <textarea id="at4" name="at4"></textarea>
                        <div class="correctAnswer">
                            <label>&nbsp;</label><input type="radio" name="correctAnswer" value="D">Correct answer</div>
                    </div>


                    <!-- answer char input  (1 CHAR !!! or TRUE/FALSE or empty input !!!) -->
                    <!--<div>-->
                        <!--<label>Input Char a right question answer</label>-->
                        <!--<input type="text" id="correctAnswer" name="correctAnswer" placeholder="D">-->
                    <!--</div>-->

                </div> 
                 <!-- end american question div --> 
                 
        <!--
        TO DO upload image from 
        user computer, and convert to Base64 ???, for send to Service(BES),
        and save in standard folder (questions) on server in format .jpg
        -->

        <div id="buttonSend">
                    <label>&nbsp;</label>

                    <input name="button_send" id="button_send"
                           type="button" value="Add To DataBase">
        </div>
        <div id="resultDB"></div>
        <input id="button_OK" type="button" value="OK" style="display: none">
     
    </form>
    
        </div>			 		
 	  </div><!--end of right area-->
 	


 	<div id="footer_area">
	
 	<p> Copyright &copy; 2014 HrTrueTest</p>
	</div>
</div>
</body>
</html>